# IntelliJ Platform Artifacts Repositories
# -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = FluentLanguage
pluginName = fluent-intellij
pluginVersion = 0.4.6

# https://youtrack.jetbrains.com/articles/IDEA-A-2100662347/IntelliJ-IDEA-2025.1-Latest-Builds
platformType = IU
platformVersion = 2026.1
pluginSinceBuild = 231

# - PsiViewer: https://plugins.jetbrains.com/plugin/227-psiviewer/versions
# Example: platformPlugins = com.intellij.java, com.jetbrains.php:203.4449.22
platformPlugins = com.github.voml.neo_theme:0.5.0,PsiViewer:2026.1
platformBundledPlugins =

# Gradle Releases -> https://github.com/gradle/gradle/releases
gradleVersion = 9.6.1
org.gradle.caching = true
org.gradle.configuration-cache = false
org.gradle.java.installations.auto-detect = true
org.gradle.java.installations.auto-download = true

# Opt-out flag for bundling Kotlin standard library.
# See https://plugins.jetbrains.com/docs/intellij/kotlin.html#kotlin-standard-library for details.
# suppress inspection "UnusedProperty"
kotlin.stdlib.default.dependency = false
